[build]
publish = "."
functions = "netlify/functions"

[functions]
node_bundler = "zisi"

[dev]
publish = "."
functions = "netlify/functions"
port = 8888

[[headers]]
for = "/"
[headers.values]
Content-Security-Policy = "frame-ancestors 'self' https://.office.com https://.officeapps.live.com https://.sharepoint.com ms-appx-web:;"